#%%
# add project root (parent of tests/) so sibling package 'hl7' can be imported
from pathlib import Path
import sys
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from hl7lite.hl7_extractor_common import extract_bed_id, _bed_id_to_wildcard, _canonical_hospitals, _canonical_units

#%%
# generated by extracting PV1.3 from hl7 messages.
if sys.argv.__len__() < 2:
    print("Usage: python tests/test_bed_id.py <bed_id_testfile>")
    sys.exit(1)
testfile = sys.argv[1]


# print(f"Known hospitals: {_canonical_hospitals.keys()}")
# print(f"known units: {_canonical_units}")

# read the file line by line
beds = []
with open(testfile, 'r') as f:
    lines = f.read().splitlines()
    
    for line in lines:
        tokens = line.split('^')
        hospital, bed_unit, bed_id = extract_bed_id(tokens)
        # print(f"original string {line} -> hospital: {hospital}, unit: {bed_unit}, bed_id: {bed_id}")
        beds.append((hospital, bed_unit, bed_id, line))
        
df = pd.DataFrame(beds, columns=['hospital', 'bed_unit', 'bed_id', 'line'])
df = df.sort_values(by=['hospital', 'bed_unit', 'bed_id']).reset_index(drop=True)

# print unique hospitals
unique_hospitals = df['hospital'].unique()
print(f"Unique hospitals in test data: {unique_hospitals}")

# print unique units per hospital
units = df.groupby(['hospital', 'bed_unit'])['bed_id'].nunique().reset_index()
# units = df[['hospital', 'bed_unit']].drop_duplicates()
# units = units.sort_values(by=['hospital', 'bed_unit']).reset_index(drop=True)
print("Unique units per hospital:")
print(units.to_markdown())

# sum total beds that are not CARTs and that are CARTS
df['is_cart'] = df['bed_unit'].str.contains('CART', case=False, na=False)
print("Number of BEDS: ", df[~df['is_cart']]['bed_id'].nunique())
print("Number of CARTS: ", df[df['is_cart']]['bed_id'].nunique())

# for hospital in unique_hospitals:
#     units = df[df['hospital'] == hospital]['bed_unit'].unique()
#     print(f"Hospital: {hospital}, Units: {units}")
    
# # print unique bed ids per unit
# beds = df[['hospital', 'bed_unit', 'bed_id']].drop_duplicates()
# beds = beds.sort_values(by=['hospital', 'bed_unit']).reset_index(drop=True)
# print("Unique beds per unit:")
# print(beds.to_markdown())

mappings = df.sort_values(by=['hospital', 'bed_unit', 'bed_id']).reset_index(drop=True)
print(f"bed_mappings: {mappings.to_markdown()}")

#%%
# check that every unit is in the list of the unit_to_canonical mapping

# for unit in df['bed_unit'].unique():
#     hosp = unit.split(' ')[0]
#     if (hosp not in _canonical_hospitals) and (unit not in _canonical_units):
#         print(f"[ERROR?] Unit '{unit}' not in canonical_units mapping.")



#%%
# for generating and updating the unit to hospital mappings.
# unitnames = set(bed_to_unit.values())
# unitnames2 = set(unit_to_hospital.keys())

# print(f"common unit names:  {unitnames.intersection(unitnames2)}")
# print(f" only in bed_to_unit: {unitnames - unitnames2}")
# print(f" only in unit_to_hospital: {unitnames2 - unitnames}")

# all_units = unitnames.union(unitnames2)
# unit_hosp = [(unit_to_hospital.get(unit, ''), unit) for unit in all_units]
# unit_hosp = sorted(unit_hosp, key=lambda x: (x[0], x[1]))
# # print(f"Total unique units: {unit_hosp}")

# for unit in unit_hosp:
#     print(f"'{unit[1]}': ('{unit[0]}', '{unit[1]}'),")
